# 基本
title: MarsWiz
email: marswiz@yeah.net
frontPageInfo1: "路旁有花，心中有歌，"
frontPageInfo2: "天上有星。"
description: >- # this means to ignore newlines until "baseurl:"
  Solid.
baseurl: "" # the subpath of your site, e.g. /blog
url: ""

# 视觉
logoBlack: "/assets/logo/logoBlack.svg"
logoWhite: "/assets/logo/logoWhite.svg"
frontPagePic: "/assets/pics/stars.webp"
navItemPath: "/assets/nav"
pagenaterItemPath: "/assets/pagenater"
postsItemPath: "/assets/posts"


# 社交（先添加社交网站名字：[社交网站]）
socialList: [mail,weixin,github,segmentfault]
# 账号与域名 （再添加社交账号和网站域名，必须为 [社交网站]_username 和 [社交网站]_site 格式。）
mail_username: ''
mail_site: 'mailto:mars_yao@yeah.net'
mail_icon: 'fa fa-envelope'

weixin_username: aboutMe
weixin_site: https://marswiz.com/
weixin_icon: "fa fa-weixin"

github_username:  marswiz
github_site: https://github.com/
github_icon: 'fa fa-github'

zhihu_username: marswiz
zhihu_site: https://zhihu.com/people/
zhihu_letter: "知"

segmentfault_username: 131597123717319
segmentfault_site: https://juejin.cn/user/
segmentfault_letter: "掘"

# 分页
paginate: 20
paginate_path: "/page:num"

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

